// Generates src/styles/tokens.css from src/styles/tokens.json (design system "InvestWise").
// Run with `npm run tokens`; the generated file is committed so the build does not depend on this step.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = resolve(root, 'src/styles/tokens.json')
const target = resolve(root, 'src/styles/tokens.css')
const tokens = JSON.parse(readFileSync(source, 'utf8'))

// "{accent}" references another color token of the same theme.
const resolveRef = (value) => value.replace(/^\{([a-z0-9-]+)\}$/, 'var(--$1)')

const themed = [...tokens.color.tokens, ...tokens.shadow.tokens]
const themeBlock = (theme) =>
  [`  color-scheme: ${theme};`, ...themed.map((t) => `  --${t.name}: ${resolveRef(t.value[theme])};`)].join('\n')

const staticLines = [
  `  --font-sans: ${tokens.type.families.sans};`,
  `  --font-serif: ${tokens.type.families.serif};`,
]
for (const group of tokens.type.groups) {
  for (const style of group.styles) {
    staticLines.push(`  --type-${style.name}-family: var(--font-${group.family});`)
    staticLines.push(`  --type-${style.name}-size: ${style.fontSize};`)
    staticLines.push(`  --type-${style.name}-line: ${style.lineHeight};`)
    staticLines.push(`  --type-${style.name}-weight: ${style.fontWeight};`)
    if (style.letterSpacing) staticLines.push(`  --type-${style.name}-tracking: ${style.letterSpacing};`)
  }
}
for (const scale of ['spacing', 'radius', 'borderWidth']) {
  for (const t of tokens[scale].tokens) staticLines.push(`  --${t.name}: ${t.value};`)
}

const css = `/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand. */

:root,
[data-theme="light"] {
${themeBlock('light')}
}

[data-theme="dark"] {
${themeBlock('dark')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${themeBlock('dark').replace(/^/gm, '  ')}
  }
}

:root {
${staticLines.join('\n')}
}
`

writeFileSync(target, css)
console.log(`tokens.css written (${themed.length} themed, ${staticLines.length} static variables)`)
